name: Project deployment

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy_docs:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Build development project
      if: steps.extract_branch.outputs.branch == 'develop'
      run: npm run development
    - name: Deploy development version
      if: steps.extract_branch.outputs.branch == 'develop'
      run: |
        cd build
        sshpass -p ${{ secrets.DEPLOY_DOCS_PASSWORD }} scp -o 'StrictHostKeyChecking no' -P ${{ secrets.DEPLOY_DOCS_PORT }} -r ./* ${{ secrets.DEPLOY_DOCS_USERNAME }}'@'${{ secrets.DEPLOY_DOCS_HOST }}':'${{ secrets.DEPLOY_DOCS_PATH_DEVELOP }};
    - name: Build final project
      if: steps.extract_branch.outputs.branch == 'master'
      run: npm run build
    - name: Deploy final version
      if: steps.extract_branch.outputs.branch == 'master'
      run: |
        cd build
        sshpass -p ${{ secrets.DEPLOY_DOCS_PASSWORD }} scp -o 'StrictHostKeyChecking no' -P ${{ secrets.DEPLOY_DOCS_PORT }} -r ./* ${{ secrets.DEPLOY_DOCS_USERNAME }}'@'${{ secrets.DEPLOY_DOCS_HOST }}':'${{ secrets.DEPLOY_DOCS_PATH_RELEASE }};
